<a href="https://colab.research.google.com/github/pranavlm/python-5-days-workshop/blob/master/day3_s2_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Write a Pandas program to create and display a one-dimensional array using series containing even numbers upto 10000
import pandas as pd
l=([i for i in range(0,10000) if i%2==0])
ds = pd.Series(l) 
print(ds)

0          0
1          2
2          4
3          6
4          8
        ... 
4995    9990
4996    9992
4997    9994
4998    9996
4999    9998
Length: 5000, dtype: int64


In [2]:
#Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type
import pandas as pd
l=([i for i in range(1000,20000) if i%5==0])
ds = pd.Series(l) 
print(ds)

0        1000
1        1005
2        1010
3        1015
4        1020
        ...  
3795    19975
3796    19980
3797    19985
3798    19990
3799    19995
Length: 3800, dtype: int64


In [3]:
# Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]¶
import pandas as pd
l1=([i for i in range(0,101) if i%2==0])
ds1 = pd.Series(l1)
l2=([i for i in range(0,100) if i%2!=0])
ds2 = pd.Series(l2)
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0       1.0
1       5.0
2       9.0
3      13.0
4      17.0
5      21.0
6      25.0
7      29.0
8      33.0
9      37.0
10     41.0
11     45.0
12     49.0
13     53.0
14     57.0
15     61.0
16     65.0
17     69.0
18     73.0
19     77.0
20     81.0
21     85.0
22     89.0
23     93.0
24     97.0
25    101.0
26    105.0
27    109.0
28    113.0
29    117.0
30    121.0
31    125.0
32    129.0
33    133.0
34    137.0
35    141.0
36    145.0
37    149.0
38    153.0
39    157.0
40    161.0
41    165.0
42    169.0
43    173.0
44    177.0
45    181.0
46    185.0
47    189.0
48    193.0
49    197.0
50      NaN
dtype: float64
Subtract two Series:
0    -1.0
1    -1.0
2    -1.0
3    -1.0
4    -1.0
5    -1.0
6    -1.0
7    -1.0
8    -1.0
9    -1.0
10   -1.0
11   -1.0
12   -1.0
13   -1.0
14   -1.0
15   -1.0
16   -1.0
17   -1.0
18   -1.0
19   -1.0
20   -1.0
21   -1.0
22   -1.0
23   -1.0
24   -1.0
25   -1.0
26   -1.0
27   -1.0
28   -1.0
29   -1.0
30   -1.0
31   -1.0
32   -1.0
33   -

In [4]:
#Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
#Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]
import pandas as pd
l1=([i for i in range(0,1000) if i%7==0])
d1 = pd.Series(l1)
l2=([i for i in range(0,1000) if i%11==0])
d2 = pd.Series(l2)
print("Compare the elements of the said Series:")
print("Equals:")
for i in range (len(l2)):
  print(i," ",d1[i]==d2[i])
print("Greater than:")
for i in range(len(l2)):
  print(i," ",d1[i]>d2[i])
print("Less than:")
for i in range(len(l2)):
  print(i," ",d1[i]<d2[i])

Compare the elements of the said Series:
Equals:
0   True
1   False
2   False
3   False
4   False
5   False
6   False
7   False
8   False
9   False
10   False
11   False
12   False
13   False
14   False
15   False
16   False
17   False
18   False
19   False
20   False
21   False
22   False
23   False
24   False
25   False
26   False
27   False
28   False
29   False
30   False
31   False
32   False
33   False
34   False
35   False
36   False
37   False
38   False
39   False
40   False
41   False
42   False
43   False
44   False
45   False
46   False
47   False
48   False
49   False
50   False
51   False
52   False
53   False
54   False
55   False
56   False
57   False
58   False
59   False
60   False
61   False
62   False
63   False
64   False
65   False
66   False
67   False
68   False
69   False
70   False
71   False
72   False
73   False
74   False
75   False
76   False
77   False
78   False
79   False
80   False
81   False
82   False
83   False
84   False
85   False
86   False
87   

In [5]:
#Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
import numpy as np
import pandas as pd
l1=([i for i in range(0,1001) if i%10==0])
np_array = np.array(l1)
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[   0   10   20   30   40   50   60   70   80   90  100  110  120  130
  140  150  160  170  180  190  200  210  220  230  240  250  260  270
  280  290  300  310  320  330  340  350  360  370  380  390  400  410
  420  430  440  450  460  470  480  490  500  510  520  530  540  550
  560  570  580  590  600  610  620  630  640  650  660  670  680  690
  700  710  720  730  740  750  760  770  780  790  800  810  820  830
  840  850  860  870  880  890  900  910  920  930  940  950  960  970
  980  990 1000]
Converted Pandas series:
0         0
1        10
2        20
3        30
4        40
       ... 
96      960
97      970
98      980
99      990
100    1000
Length: 101, dtype: int64


In [6]:
#Write a Pandas program to convert a given Series to an array.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


In [7]:
#Write a Pandas program to sort a given Series
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]
import pandas as pd
s = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
0          100
1          200
2          300
6       300.12
3          400
7          400
4          500
9        great
8           is
10    language
5       python
dtype: object


In [8]:
#Write a Pandas program to create a subsets of a given series based on value and condition.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
#value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5
import pandas as pd
l1=([i for i in range(0,1001) if i%10==0])
s = pd.Series(l1)
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n=7
new_s = s[s%n==0]
print(new_s)
n=5
new_s = s[s%n==0]
print(new_s)

Original Data Series:
0         0
1        10
2        20
3        30
4        40
       ... 
96      960
97      970
98      980
99      990
100    1000
Length: 101, dtype: int64

Subset of the above Data Series:
0       0
7      70
14    140
21    210
28    280
35    350
42    420
49    490
56    560
63    630
70    700
77    770
84    840
91    910
98    980
dtype: int64
0         0
1        10
2        20
3        30
4        40
       ... 
96      960
97      970
98      980
99      990
100    1000
Length: 101, dtype: int64


In [9]:
#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000
import pandas as pd
l=[]
for val in range(0,1001):
  if val > 1: 
        for n in range(2, val//2 + 2): 
            if (val % n) == 0: 
                break
            else: 
                if n == val//2 + 1: 
                    l.append(val)
s = pd.Series(data = l)
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        3
1        5
2        7
3       11
4       13
      ... 
162    971
163    977
164    983
165    991
166    997
Length: 167, dtype: int64
Mean of the said Data Series:
455.8383233532934
Standard deviation of the said Data Series:
297.0201672063572


In [10]:
#Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000
import pandas as pd
l1=([i for i in range(0,1001) if i%7!=0 and i%2!=0])

l2=([i for i in range(0,1001) if i%2==0 and i%5!=0])
l3=([i for i in range(0,1001) if i%2!=0 and i%3!=0])
print(len(l1),len(l2),len(l3))
df = pd.DataFrame({'X':l1, 'Y':l2,'Z':l3});

                   
print(df)                                                                                                                                     

429 400 333


ValueError: ignored

In [ ]:
#Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields
import pandas as pd
df = pd.read_csv('movies.csv')
#Display the first 10 rows
small_df = df[['rating','budget','year']]
result = small_df.head(10)
print("First 10 rows of the DataFrame:")
print(result)

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('movies.csv')
print("sorted by country")
result = df.sort_values('country')
print(result)
print("sorted by lang")
result = df.sort_values('language')
print(result)


In [ ]:
import pandas as pd
df = pd.read_csv('movies.csv')
small_df = df[['rating','budget','year']]
result = small_df.sort_values('year')
print("DataFrame based on release date.")
print(result)

In [ ]:
import pandas as pd
df = pd.read_csv('Python_marks.csv')
mean1 = df['marks'].mean()
max1 = df['marks'].max()
min1 = df['marks'].min()
std1 = df['marks'].std() 
print("file content: ",df)
print ('Mean : ' + str(mean1))
print ('S.D: ' + str(std1))
print ('Minimum : ' + str(min1))
print ('Maximum : ' + str(max1))

In [18]:

import numpy as np
x = np.random.random((4,4))
print(x)
print("2nd and 3rd rows of the above array:")
y= x[1:3, :]
print(y)

[[0.24772158 0.68976756 0.88291391 0.71672077]
 [0.76399847 0.15059362 0.5293871  0.9015159 ]
 [0.25765791 0.97010072 0.05930644 0.0905289 ]
 [0.82609587 0.52839105 0.43521085 0.15627056]]
2nd and 3rd rows of the above array:
[[0.76399847 0.15059362 0.5293871  0.9015159 ]
 [0.25765791 0.97010072 0.05930644 0.0905289 ]]


In [19]:
#Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.¶
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.17495266 0.93049825 0.55609352 0.90144025 0.93025223 0.79690435
  0.98296956 0.74942589 0.73312178 0.44911556]
 [0.62333168 0.62129622 0.08675394 0.88889662 0.50792474 0.0291783
  0.09218165 0.96679747 0.88303576 0.94919055]
 [0.14897799 0.59947762 0.03225878 0.752425   0.31664996 0.16415877
  0.86227958 0.95212532 0.08374259 0.61523704]
 [0.0110124  0.10216236 0.67257692 0.09379323 0.41240754 0.52174616
  0.30426739 0.77648858 0.36288919 0.27059383]
 [0.63537839 0.84491681 0.89558624 0.7447828  0.82868661 0.07079935
  0.93829232 0.47136057 0.0596431  0.3197421 ]
 [0.66967107 0.00553539 0.12250039 0.54225992 0.05429792 0.14825148
  0.31908537 0.46232633 0.05449997 0.11195038]
 [0.7931113  0.48353989 0.54118873 0.39518079 0.43639942 0.38998443
  0.86527429 0.8924946  0.15690764 0.69228508]
 [0.67273256 0.90763941 0.67112339 0.26220629 0.47633189 0.39583041
  0.03359123 0.80020778 0.27679951 0.62169084]
 [0.99935384 0.0876457  0.63839827 0.95724768 0.87647179 0.104428

In [20]:
#Write a NumPy program to generate 8 random integers between 100 and 300
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[110 120 242 202 259 164 233 286]


In [21]:
#Write a NumPy program to create a random integer nos of size 20 and sort it.¶
import numpy as np
x=np.arange(20)
np.random.shuffle(x)
print(x)
x.sort()
print(x)

[16  6  0 15  5  1 12 14 18  7  4  3 13 10  8 11  2 17 19  9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
